---
helpFiles:
- show: true
  maxLength: 200
  itemName: "help\\readme.txt"
  originFileName: "README.md"
- show: true
  maxLength: 200
  itemName: "help\\how-to-configure.txt"
  originFileName: "how-to-configure.md"
- show: true
  maxLength: 200
  itemName: "help\\changes.txt"
  originFileName: "changes.md"
defaultFormat:
  allMetadataDir:
    show: true
    maxLength: 200
    itemName: "metadata\\%NUMBER%. %NAME%=%VALUE%.metadata"
  allMetadataFile:
    show: true
    maxLength: 200
    itemName: "%DOCUMENT%.metadata"
  preview:
    show: true
    maxLength: 200
    itemName: "%DOCUMENT%.preview"
    maxSize: 10000
  contents:
    show: true
    maxLength: 200
    itemName: "%DOCUMENT%.txt"
    maxSize: 50000000
  linesAsfiles:
    show: true
    maxLength: 75
    itemName: "%NUMBER% %LINE%.line"
    minLength: 60
    numberOfLines: 20
specificFormats:
- allMetadataDir:
    show: true
    maxLength: 200
    itemName: "metadata\\%NUMBER%. %NAME%=%VALUE%.metadata"
  allMetadataFile:
    show: true
    maxLength: 200
    itemName: "%DOCUMENT%.metadata"
  preview:
    show: true
    maxLength: 200
    itemName: "%DOCUMENT%.preview"
    maxSize: 10000
  contents:
    show: true
    maxLength: 200
    itemName: "%DOCUMENT%.txt"
    maxSize: 50000000
  linesAsfiles:
    show: true
    maxLength: 75
    itemName: "%NUMBER% %LINE%.line"
    minLength: 60
    numberOfLines: 20
  extension: "pdf"
  specificMetadata:
  - show: true
    maxLength: 200
    itemName: "%NUMBER%. title=%VALUE%.metadata"
    metadataName: "pdf:docinfo:title"
  - show: true
    maxLength: 200
    itemName: "%NUMBER%. creator=%VALUE%.metadata"
    metadataName: "pdf:docinfo:creator"
- allMetadataDir:
    show: true
    maxLength: 200
    itemName: "metadata\\%NUMBER%. %NAME%=%VALUE%.metadata"
  allMetadataFile:
    show: true
    maxLength: 200
    itemName: "%DOCUMENT%.metadata"
  preview:
    show: true
    maxLength: 200
    itemName: "%DOCUMENT%.preview"
    maxSize: 10000
  contents:
    show: true
    maxLength: 200
    itemName: "%DOCUMENT%.txt"
    maxSize: 50000000
  linesAsfiles:
    show: true
    maxLength: 75
    itemName: "%NUMBER% %LINE%.line"
    minLength: 60
    numberOfLines: 20
  extension: "docx"
  specificMetadata: null
